### PR TITLE
Circle ci

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
hum ... https://4-227720375-gh.circle-artifacts.com/0/dev/index.html

**Comment by tomMoral** [comment]
If I may, why do we use circleCI instead of github actions?

**Comment by agramfort** [comment]
because i know how to do it fast in circleci :)

**Comment by tomMoral** [comment]
It is a fair point!
There seems to be a strange thing with the artifact no?

**Comment by agramfort** [comment]
doing it not from a fork

yes the artifact has a pb...

**Pull request closed without merging**
