### PR TITLE
[Doc] Search bar with bootstrap theme

### LINKED ISSUE #271: BUG DOC search is not working on the doc website
At least on my side: it gets suck with "Searching ...":
image

https://benchopt.github.io/search.html?q=autocompletion&check_keywords=yes&area=default

### PR DESCRIPTION
**Pull request by tanglef**
Fixes #271 by adding the proposed html file.

### CODE REVIEW

**Comment by tomMoral** [comment]
It seems to be working!!! thx @tanglef 
https://1174-227720375-gh.circle-artifacts.com/0/dev/search.html?q=test&check_keywords=yes&area=default

**Review by tomMoral — APPROVED** [review]
LGTM!

**Comment by tanglef** [comment]
Just for posterity (like in a few others): when/if sphinx-bootstrap-theme fixes this bug we should remember to revert this PR.

**Comment by tomMoral** [comment]
Is there any PR in the sphinx-bootstrap-theme repo to track this? If yes, could you add a link here?

**Comment by tanglef** [comment]
Yes there is, it is the PR mentioned in the connected issue (#271)

**Comment by tomMoral** [comment]
**Note**: Revert this change if ryan-roemer/sphinx-bootstrap-theme#213 is closed.

**Pull request merged**
