### PR TITLE
Website improvements

### PR DESCRIPTION
**Pull request by TomDLT**
A bunch of improvements for the website (see each commit).
In particular, it makes the sidebar more compact and with larger indents:
before:imageafter:image

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by mathurinm** [comment]
It's much better this way, thanks @TomDLT!

**Comment by tomMoral** [comment]
It is much better but we still have some issues:
image

The body starts before the end of the top bar. Not sure how to fix this.

**Comment by TomDLT** [comment]
This is not a problem of the sidebar, but it is a problem of the navbar at the top. For medium size screens, the content is too long and it creates two or three lines. #365

There is probably a more robust/clean solution, but as a workaround I have removed the search box for medium screens. I also removed the link to "write a benchmark", which is long and already highlighted in the frontpage. It is still present in the "Site" dropdown menu.

**Comment by tomMoral** [comment]
Great, this is very nice now :)

thanks a lot @TomDLT !!!

**Pull request merged**
