### PR TITLE
ENH add sklearn solver for OLS/NNLS

### PR DESCRIPTION
**Pull request by TomDLT**

### CODE REVIEW

**Comment by josephsalmon** [comment]
Thx @TomDLT ! Looks good too me.
The only minor issue for me is having only *one point* for this solver (the underlying BLAS function seems to rely on SVD).
Not sure how to proceed with such kind of solvers though.

**Comment by agramfort** [comment]
@TomDLT can you look into the CI issue? thx

**Comment by agramfort** [comment]
diff looks good but I think we should focus our efforts to produce meaningful and convincing figures to advertise what this piece of software enables.

**Comment by TomDLT** [comment]
I fixed the error, adding a check for failed import in `test_solver`.

I also added a scikit-learn solver for NNLS, using `Lasso(alpha=1e-10, positive=True)`, which is hacky but converges to the same solution.

**Comment by agramfort** [comment]
do you have some nice bench plots to share?

>

**Pull request merged**
