### PR TITLE
Toggle shaded areas

### LINKED ISSUE #228: ENH/PLT: add way to toggle shaded areas on and off
Sometimes I use `-r 10` to get less bumpy curves, but it may get hard to read with the shaded areas and it could be nice to disable them. It's not a critical feature, but if it's easy to do then WDYT ?
image

### PR DESCRIPTION
**Pull request by tanglef**
This introduces a button to toggle on/off the shaded areas (and thus resolves #228 )
| On | Off |
:----------------------:|:------------------------------:
Capture d’écran de 2021-12-03 15-08-23 | Capture d’écran de 2021-12-03 15-08-29

### CODE REVIEW

**Comment by agramfort** [comment]
it does not work for me. When I hide the quantiles it removes some of the
legend. It should not

>

**Comment by tanglef** [comment]
Do you have a case where it happens I could reproduce ? (I fixed the histogram, but can't seem to reproduce that issue for objective curves)

**Comment by agramfort** [comment]
in the screenshot you shared do you see that the legend is not the same?

>

**Comment by tanglef** [comment]
It's just me when I made the rectangle to take part of my screen in capture. But if you want I can take with the whole legend:
| off | on |
:----------:|:--------:
Capture d’écran de 2021-12-03 18-25-21 | Capture d’écran de 2021-12-03 18-25-14

**Comment by tanglef** [comment]
To be even more precise as to what I turn on/off: I only toggle on/off the visibility of traces in the plotly graph that have no name attribute (and if a trace is in the legend, then it has a name so its visibility is not modified and thus the legend is not either).

**Comment by agramfort** [comment]
https://user-images.githubusercontent.com/161052/144647177-b18990b3-3b3b-42e4-86c2-b87b4f1d28c6.mov

**Comment by tanglef** [comment]
Okay, I saw [a post](https://community.plotly.com/t/scatter-plot-legend-not-showing-for-a-single-trace/21713) in plotly doc about that (the legend disappears because this is now a single trace graph and thus we need to specify that the legend is visible). I'll take care of it tomorrow or later (can't right now).
Thank you for noticing that!

**Review by agramfort — APPROVED** [review]
works for me !

**Comment by agramfort** [comment]
thx @tanglef

**Pull request merged**
