### PR TITLE
ENH allow multi output objective

### PR DESCRIPTION
**Pull request by tomMoral**
Objective can now return a dictionary with multiple values that will be recorded.
this allow to monitor different metrics to display in the results.

### CODE REVIEW

**Comment by agramfort** [comment]
Is this backward compatible?

**Comment by tomMoral** [comment]
yep!

**Review by agramfort — APPROVED** [review]
Amen !

we'll bother about the doc later ;)

**Comment by tomMoral** [comment]
I think we just miss a bit more doc on this one before merging.

**Pull request merged**
