### PR TITLE
FIX escape brackets in command line when running in env

### LINKED ISSUE #366: BUG using --env breaks solver name in configuration file
In Lasso benchmark, on this PR: https://github.com/benchopt/benchmark_lasso/pull/82

```
(base) ➜  lasso git:(quickstart) ✗ benchopt run . --config example_config.yml --env
/tmp/tmpig1um8vo:8: no matches found: python-pgd[use_acceleration=True]
(base) ➜  lasso git:(quickstart) ✗ benchopt run . --config example_config.yml      
Benchopt is running
leukemia                                                                                                                            
  |--Lasso Regression[fit_intercept=False,reg=0.1]                                                                                  
    |--lars: done                            
```

because when running in env, [ ] are parsed as regex @tomMoral ?

### PR DESCRIPTION
**Pull request by tomMoral**
Should fix #366 , cc @mathurinm

### CODE REVIEW

**Comment by mathurinm** [comment]
It seems to fail for objectives :
```
(base) ➜  lasso git:(quickstart) ✗ benchopt run . --config example_config.yml --env
Usage: benchopt run [OPTIONS] BENCHMARK
Try 'benchopt run -h' for help.

Error: Invalid value: Patterns ['Lasso Regression\\[fit_intercept=False,reg=0.1\\]'] did not match any objective.
Available objectives are:
- Lasso Regression[fit_intercept=True,reg=0.5]
```

**Comment by tomMoral** [comment]
This should be better @mathurinm

**Review by TomDLT — APPROVED** [review]
LGTM. I had the same issue and found the [same fix](https://github.com/benchopt/benchopt/pull/362/files#diff-f2db6eb8023e77ca3c40f7aafb1e99f37a9cf9ff7f8e004c104be764498f3af8R244) in #362.

**Comment by tomMoral** [comment]
Let's merge then.

**Pull request merged**
