### PR TITLE
ENH use current working directory as default in CLI

### LINKED ISSUE #382: ENH support run command without `.` by default
Reading the doc, it is not always clear that one should run the command as follows:

```
benchopt run . --config pathological.yml
```

One would rather like a command like 

```
benchopt run --config pathological.yml
```
to work out of the box.

### PR DESCRIPTION
**Pull request by tanglef**
Fixes #382
Not exactly sure how to test this though....

### CODE REVIEW

**Comment by tanglef** [comment]
`urllib` error on leukemia. Will trigger back the CI tmrw...

**Review by tomMoral — COMMENTED** [review]
this seems ok to do that.
Questions:
- How does it fare with autocompletion?
- Could you test this by checking that not passing a repo tells you that you don't have a `objective.py` function in the current repo?

**Comment by mathurinm** [comment]
This is a great feature !

:heavy_check_mark:  The error is raised if we're not in a valid benchmark folder:
```
(base) ➜  ~ benchopt run 
Usage: benchopt run [OPTIONS] [BENCHMARK]
Try 'benchopt run -h' for help.

Error: Invalid value: The folder '/home/mathurin' does not contain `objective.py`.
Make sure you provide the path to a valid benchmark.
```

:checkmark: autocompletion works nice:

image



LGTM !

**Comment by tomMoral** [comment]
I was speaking of the auto completion when not putting `.`. I think it is not working yet as `benchopt run -s <tab>` gives nothing on my side. In the autocompletion command, if no benchmark is found, we should also default to `.`

**Comment by tanglef** [comment]
This finally works

Capture d’écran de 2022-05-13 11-16-55

**Review by tomMoral — APPROVED** [review]
LGTM! thansk @tanglef

**Pull request merged**
