### PR TITLE
Add axis types semilog and linear

### LINKED ISSUE #222: ENH: add normal scale and semilogx as axis types
For some objectives it may make sense to have a normal plot, without logscale (here I have vanishing values in my custom objective) 
image

we may also add a semilogx option. 

@tanglef the plotly :mage:

### PR DESCRIPTION
**Pull request by tanglef**
Fixes #222 by adding semilog-x and linear graph axis types (poke @mathurinm )

### CODE REVIEW

**Comment by mathurinm** [comment]
Looking good! Thx @tanglef 
image
image

**Comment by agramfort** [comment]
merge if happy

>

**Comment by mathurinm** [comment]
Is it easy to keep the same `axis type` selected as long as `value` (here, objective value and support size) does not change ? 

Currently when I change Objective, it goes back to semilogy scale

**Comment by tanglef** [comment]
You are right, but that means there's a bigger flaw about the current (and past) implementations.
The axis type is the same across "kinds" but the dropdown menu still changes when we change the type.
I will look into that and find a way to make it right for objectives too.

**Comment by tanglef** [comment]
The way I found to make the axis type "independent" was to remove the id list made from Python that was passed to Js through the `onChange` method and update directly the plots concerned using Js `onChange`.

**Review by tomMoral — APPROVED** [review]
This LGTM! Thanks a lot @tanglef ! :)

**Pull request merged**
