### PR TITLE
DOC add link to template in doc, also update missing solver

### PR DESCRIPTION
**Pull request by mathurinm**

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
don't know why CIs fail...

**Comment by mathurinm** [comment]
It breaks complaining that the repo is not cloned, but I think it is because of pyjulia instead because the repo is cloned

**Comment by agramfort** [comment]
so main branch is broken again?

>

**Comment by tomMoral** [comment]
Yes, since the 27/11/21, I guess an update in `pyjulia` broke the install again.
I did not have time to investigate yet.

**Comment by mathurinm** [comment]
Yes that's probable, see this commit from 25/11: https://github.com/JuliaPy/pyjulia/commit/39dfcd217f7644058bcca64849d062e31a8b5c1c 

I'm trying to fix in #252

**Comment by agramfort** [comment]
green CI merging !

**Pull request merged**
