### PR TITLE
Scales plotly option

### PR DESCRIPTION
**Pull request by tanglef**
- Add an option to toggle between semilogy plots and loglog with plotly (cc @mathurinm). It presents iself as a dropdown menu and the active element is showed. Default is loglog (current plots). (Of course after clicking it shrinks back to a normal menu, the image below is to show how options are displayed)
- Comments in CSS added for clarity.

Capture d’écran de 2021-07-01 16-57-16

### CODE REVIEW

**Comment by mathurinm** [comment]
Thanks @tanglef it rocks. I tested it locally and it works as expected :tada: 

really really small comment, the box seems to overlap a bit with the title of the plot 
image

**Review by agramfort — APPROVED** [review]
nice !

**Comment by tanglef** [comment]
Because the spacing for  the title is very "figure-dependant" I rather put the options on the side to avoid having to make ugly fixes for now.

**Review by tomMoral — APPROVED** [review]
LGTM.

Thanks a lot @tanglef for adding the comments!

**Pull request merged**
