### PR TITLE
Scaling axis once for all plotly

### PR DESCRIPTION
**Pull request by tanglef**
Now, for each dataset the user does not have to change the axis type (loglog or semilog) when switching plots / hyperparameters.
This is an issue @mathurinm raised to me and it is more convenient for users.

Also, I took advantage of returning into these parts of the code to remove some warnings/uncaught exceptions that were displayed in the js console.

### CODE REVIEW

**Comment by tanglef** [comment]
It seems circleci couldn't install the packages needed for the tests... Any idea about that?

**Comment by mathurinm** [comment]
It does not seem that you added new requirements in this PR, right ? Can you push an empty commit to trigger circle again, sometimes it fixes time out errors

**Comment by tanglef** [comment]
> It does not seem that you added new requirements in this PR, right ? Can you push an empty commit to trigger circle again, sometimes it fixes time out errors

No, I did not. And it seems to do the same thing (the error begins within the scipy install).

**Comment by tanglef** [comment]
Works with #202

**Review by tomMoral — APPROVED** [review]
This is a super nice addition! Thanks @tanglef

**Pull request merged**
